// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getRecentActivitiesForUser = `-- name: GetRecentActivitiesForUser :many
SELECT id, user_id, event_type, payload, created_at FROM activity_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) GetRecentActivitiesForUser(ctx context.Context, userID uuid.UUID) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity_log (user_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertActivityParams struct {
	UserID    uuid.UUID
	EventType string
	Payload   pqtype.NullRawMessage
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity, arg.UserID, arg.EventType, arg.Payload)
	return err
}
