// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_api_keys.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createAgentAPIKey = `-- name: CreateAgentAPIKey :one
INSERT INTO agent_api_keys (
  user_id,
  name,
  key_prefix,
  key_hash,
  scopes_json,
  status,
  created_by_ip,
  expires_at,
  notes,
  usage_count,
  last_seen_context_json
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json
`

type CreateAgentAPIKeyParams struct {
	UserID              uuid.UUID
	Name                string
	KeyPrefix           string
	KeyHash             string
	ScopesJson          json.RawMessage
	Status              string
	CreatedByIp         sql.NullString
	ExpiresAt           sql.NullTime
	Notes               sql.NullString
	UsageCount          int32
	LastSeenContextJson json.RawMessage
}

func (q *Queries) CreateAgentAPIKey(ctx context.Context, arg CreateAgentAPIKeyParams) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAgentAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ScopesJson,
		arg.Status,
		arg.CreatedByIp,
		arg.ExpiresAt,
		arg.Notes,
		arg.UsageCount,
		arg.LastSeenContextJson,
	)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}

const getAgentAPIKeyByHash = `-- name: GetAgentAPIKeyByHash :one
SELECT id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json FROM agent_api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAgentAPIKeyByHash(ctx context.Context, keyHash string) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAgentAPIKeyByHash, keyHash)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}

const getAgentAPIKeyByIDForUser = `-- name: GetAgentAPIKeyByIDForUser :one
SELECT id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json FROM agent_api_keys
WHERE id = $1 AND user_id = $2
`

type GetAgentAPIKeyByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAgentAPIKeyByIDForUser(ctx context.Context, arg GetAgentAPIKeyByIDForUserParams) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAgentAPIKeyByIDForUser, arg.ID, arg.UserID)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}

const listAgentAPIKeysByUser = `-- name: ListAgentAPIKeysByUser :many
SELECT id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json FROM agent_api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgentAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]AgentApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAgentAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentApiKey
	for rows.Next() {
		var i AgentApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.ScopesJson,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedByIp,
			&i.LastUsedIp,
			&i.LastUsedUserAgent,
			&i.Notes,
			&i.UsageCount,
			&i.LastSeenContextJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentAPIKeyExpired = `-- name: MarkAgentAPIKeyExpired :one
UPDATE agent_api_keys
SET status = 'expired'
WHERE id = $1
RETURNING id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json
`

func (q *Queries) MarkAgentAPIKeyExpired(ctx context.Context, id uuid.UUID) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, markAgentAPIKeyExpired, id)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}

const markAgentAPIKeyUsed = `-- name: MarkAgentAPIKeyUsed :one
UPDATE agent_api_keys
SET last_used_at = $2,
    last_used_ip = $3,
    last_used_user_agent = $4,
    usage_count = usage_count + 1,
    last_seen_context_json = $5
WHERE id = $1
RETURNING id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json
`

type MarkAgentAPIKeyUsedParams struct {
	ID                  uuid.UUID
	LastUsedAt          sql.NullTime
	LastUsedIp          sql.NullString
	LastUsedUserAgent   sql.NullString
	LastSeenContextJson json.RawMessage
}

func (q *Queries) MarkAgentAPIKeyUsed(ctx context.Context, arg MarkAgentAPIKeyUsedParams) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, markAgentAPIKeyUsed,
		arg.ID,
		arg.LastUsedAt,
		arg.LastUsedIp,
		arg.LastUsedUserAgent,
		arg.LastSeenContextJson,
	)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}

const revokeAgentAPIKey = `-- name: RevokeAgentAPIKey :one
UPDATE agent_api_keys
SET status = 'revoked',
    revoked_at = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, key_prefix, key_hash, scopes_json, status, created_at, last_used_at, expires_at, revoked_at, created_by_ip, last_used_ip, last_used_user_agent, notes, usage_count, last_seen_context_json
`

type RevokeAgentAPIKeyParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeAgentAPIKey(ctx context.Context, arg RevokeAgentAPIKeyParams) (AgentApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeAgentAPIKey, arg.ID, arg.UserID, arg.RevokedAt)
	var i AgentApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.ScopesJson,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByIp,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.Notes,
		&i.UsageCount,
		&i.LastSeenContextJson,
	)
	return i, err
}
