// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
  user_id,
  action,
  resource_type,
  resource_id,
  metadata,
  ip_address,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at
`

type CreateAuditLogParams struct {
	UserID       uuid.NullUUID
	Action       string
	ResourceType string
	ResourceID   uuid.NullUUID
	Metadata     pqtype.NullRawMessage
	IpAddress    pqtype.Inet
	CreatedAt    time.Time
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :exec
DELETE FROM audit_logs
WHERE user_id = $1 AND created_at < $2
`

type DeleteAuditLogsBeforeParams struct {
	UserID    uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, arg DeleteAuditLogsBeforeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuditLogsBefore, arg.UserID, arg.CreatedAt)
	return err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id uuid.UUID) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogCount = `-- name: GetAuditLogCount :one
SELECT COUNT(*) FROM audit_logs
WHERE user_id = $1
`

func (q *Queries) GetAuditLogCount(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditLogsByAction = `-- name: GetAuditLogsByAction :many
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE user_id = $1 AND action = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetAuditLogsByActionParams struct {
	UserID uuid.NullUUID
	Action string
	Limit  int32
}

func (q *Queries) GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByAction, arg.UserID, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByDateRange = `-- name: GetAuditLogsByDateRange :many
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE user_id = $1 AND created_at BETWEEN $2 AND $3
ORDER BY created_at DESC
`

type GetAuditLogsByDateRangeParams struct {
	UserID      uuid.NullUUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) GetAuditLogsByDateRange(ctx context.Context, arg GetAuditLogsByDateRangeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByDateRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByResource = `-- name: GetAuditLogsByResource :many
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE user_id = $1 AND resource_type = $2 AND resource_id = $3
ORDER BY created_at DESC
`

type GetAuditLogsByResourceParams struct {
	UserID       uuid.NullUUID
	ResourceType string
	ResourceID   uuid.NullUUID
}

func (q *Queries) GetAuditLogsByResource(ctx context.Context, arg GetAuditLogsByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByResource, arg.UserID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUser = `-- name: GetAuditLogsByUser :many
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAuditLogsByUserParams struct {
	UserID uuid.NullUUID
	Limit  int32
}

func (q *Queries) GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAuditLogs = `-- name: GetRecentAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, metadata, ip_address, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRecentAuditLogsParams struct {
	UserID uuid.NullUUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetRecentAuditLogs(ctx context.Context, arg GetRecentAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAuditLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
