// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEmailAccount = `-- name: CreateEmailAccount :one
INSERT INTO email_accounts (
    user_id,
    email,
    imap_host,
    imap_port,
    imap_user,
    encrypted_imap_password
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, email, imap_host, imap_port, imap_user, encrypted_imap_password, created_at, updated_at
`

type CreateEmailAccountParams struct {
	UserID                uuid.UUID
	Email                 string
	ImapHost              string
	ImapPort              int32
	ImapUser              string
	EncryptedImapPassword []byte
}

func (q *Queries) CreateEmailAccount(ctx context.Context, arg CreateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRowContext(ctx, createEmailAccount,
		arg.UserID,
		arg.Email,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapUser,
		arg.EncryptedImapPassword,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUser,
		&i.EncryptedImapPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailAccount = `-- name: DeleteEmailAccount :exec
DELETE FROM email_accounts
WHERE id = $1 AND user_id = $2
`

type DeleteEmailAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteEmailAccount(ctx context.Context, arg DeleteEmailAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailAccount, arg.ID, arg.UserID)
	return err
}

const getEmailAccountByID = `-- name: GetEmailAccountByID :one
SELECT id, user_id, email, imap_host, imap_port, imap_user, encrypted_imap_password, created_at, updated_at FROM email_accounts
WHERE id = $1 AND user_id = $2
`

type GetEmailAccountByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetEmailAccountByID(ctx context.Context, arg GetEmailAccountByIDParams) (EmailAccount, error) {
	row := q.db.QueryRowContext(ctx, getEmailAccountByID, arg.ID, arg.UserID)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUser,
		&i.EncryptedImapPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailAccountsByUser = `-- name: ListEmailAccountsByUser :many
SELECT id, user_id, email, imap_host, imap_port, imap_user, encrypted_imap_password, created_at, updated_at FROM email_accounts
WHERE user_id = $1
ORDER BY email
`

func (q *Queries) ListEmailAccountsByUser(ctx context.Context, userID uuid.UUID) ([]EmailAccount, error) {
	rows, err := q.db.QueryContext(ctx, listEmailAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAccount
	for rows.Next() {
		var i EmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapUser,
			&i.EncryptedImapPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailAccount = `-- name: UpdateEmailAccount :one
UPDATE email_accounts
SET
    email = $3,
    imap_host = $4,
    imap_port = $5,
    imap_user = $6,
    encrypted_imap_password = $7,
    updated_at = NOW()
WHERE
    id = $1 AND user_id = $2
RETURNING id, user_id, email, imap_host, imap_port, imap_user, encrypted_imap_password, created_at, updated_at
`

type UpdateEmailAccountParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Email                 string
	ImapHost              string
	ImapPort              int32
	ImapUser              string
	EncryptedImapPassword []byte
}

func (q *Queries) UpdateEmailAccount(ctx context.Context, arg UpdateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRowContext(ctx, updateEmailAccount,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapUser,
		arg.EncryptedImapPassword,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUser,
		&i.EncryptedImapPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
