// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files_drop_source.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFileDropSource = `-- name: GetFileDropSource :one
SELECT 
    f.id,
    f.filename,
    u.token,
    fol.name as folder_name
FROM files f
INNER JOIN upload_tokens u ON f.drop_source_id = u.id
INNER JOIN folders fol ON u.target_folder_id = fol.id
WHERE f.id = $1
`

type GetFileDropSourceRow struct {
	ID         uuid.UUID
	Filename   string
	Token      string
	FolderName string
}

func (q *Queries) GetFileDropSource(ctx context.Context, id uuid.UUID) (GetFileDropSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getFileDropSource, id)
	var i GetFileDropSourceRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Token,
		&i.FolderName,
	)
	return i, err
}
