// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_requests.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addUploadedFile = `-- name: AddUploadedFile :one
UPDATE file_requests
SET uploaded_files = uploaded_files || $2,
    updated_at = $3
WHERE id = $1
RETURNING id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at
`

type AddUploadedFileParams struct {
	ID            uuid.UUID
	UploadedFiles pqtype.NullRawMessage
	UpdatedAt     time.Time
}

func (q *Queries) AddUploadedFile(ctx context.Context, arg AddUploadedFileParams) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, addUploadedFile, arg.ID, arg.UploadedFiles, arg.UpdatedAt)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileRequest = `-- name: CreateFileRequest :one
INSERT INTO file_requests (
  owner_id,
  token,
  description,
  expires_at,
  max_file_size,
  is_active,
  uploaded_files,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at
`

type CreateFileRequestParams struct {
	OwnerID       uuid.UUID
	Token         string
	Description   sql.NullString
	ExpiresAt     sql.NullTime
	MaxFileSize   sql.NullInt64
	IsActive      sql.NullBool
	UploadedFiles pqtype.NullRawMessage
	CreatedAt     time.Time
}

func (q *Queries) CreateFileRequest(ctx context.Context, arg CreateFileRequestParams) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, createFileRequest,
		arg.OwnerID,
		arg.Token,
		arg.Description,
		arg.ExpiresAt,
		arg.MaxFileSize,
		arg.IsActive,
		arg.UploadedFiles,
		arg.CreatedAt,
	)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFileRequest = `-- name: DeleteFileRequest :exec
DELETE FROM file_requests
WHERE id = $1 AND owner_id = $2
`

type DeleteFileRequestParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteFileRequest(ctx context.Context, arg DeleteFileRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileRequest, arg.ID, arg.OwnerID)
	return err
}

const getExpiredRequests = `-- name: GetExpiredRequests :many
SELECT id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at FROM file_requests
WHERE is_active = true AND expires_at < NOW()
`

func (q *Queries) GetExpiredRequests(ctx context.Context) ([]FileRequest, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileRequest
	for rows.Next() {
		var i FileRequest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Token,
			&i.Description,
			&i.ExpiresAt,
			&i.MaxFileSize,
			&i.IsActive,
			&i.UploadedFiles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileRequestByID = `-- name: GetFileRequestByID :one
SELECT id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at FROM file_requests
WHERE id = $1
`

func (q *Queries) GetFileRequestByID(ctx context.Context, id uuid.UUID) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, getFileRequestByID, id)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileRequestByToken = `-- name: GetFileRequestByToken :one
SELECT id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at FROM file_requests
WHERE token = $1 AND is_active = true
`

func (q *Queries) GetFileRequestByToken(ctx context.Context, token string) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, getFileRequestByToken, token)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileRequestsByOwner = `-- name: GetFileRequestsByOwner :many
SELECT id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at FROM file_requests
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileRequestsByOwner(ctx context.Context, ownerID uuid.UUID) ([]FileRequest, error) {
	rows, err := q.db.QueryContext(ctx, getFileRequestsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileRequest
	for rows.Next() {
		var i FileRequest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Token,
			&i.Description,
			&i.ExpiresAt,
			&i.MaxFileSize,
			&i.IsActive,
			&i.UploadedFiles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFileRequest = `-- name: RevokeFileRequest :one
UPDATE file_requests
SET is_active = false,
    updated_at = $2
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at
`

type RevokeFileRequestParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) RevokeFileRequest(ctx context.Context, arg RevokeFileRequestParams) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, revokeFileRequest, arg.ID, arg.UpdatedAt, arg.OwnerID)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileRequest = `-- name: UpdateFileRequest :one
UPDATE file_requests
SET description = $2,
    expires_at = $3,
    max_file_size = $4,
    is_active = $5,
    uploaded_files = $6,
    updated_at = $7
WHERE id = $1 AND owner_id = $8
RETURNING id, owner_id, token, description, expires_at, max_file_size, is_active, uploaded_files, created_at, updated_at
`

type UpdateFileRequestParams struct {
	ID            uuid.UUID
	Description   sql.NullString
	ExpiresAt     sql.NullTime
	MaxFileSize   sql.NullInt64
	IsActive      sql.NullBool
	UploadedFiles pqtype.NullRawMessage
	UpdatedAt     time.Time
	OwnerID       uuid.UUID
}

func (q *Queries) UpdateFileRequest(ctx context.Context, arg UpdateFileRequestParams) (FileRequest, error) {
	row := q.db.QueryRowContext(ctx, updateFileRequest,
		arg.ID,
		arg.Description,
		arg.ExpiresAt,
		arg.MaxFileSize,
		arg.IsActive,
		arg.UploadedFiles,
		arg.UpdatedAt,
		arg.OwnerID,
	)
	var i FileRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Description,
		&i.ExpiresAt,
		&i.MaxFileSize,
		&i.IsActive,
		&i.UploadedFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
