// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files_with_drop_source.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getFilesWithDropSource = `-- name: GetFilesWithDropSource :many
SELECT
    f.id,
    f.filename,
    f.file_path,
    f.file_size,
    f.starred,
    f.created_at,
    f.updated_at,
    f.encrypted_metadata,
    f.drop_source_id,
    u.token as drop_token,
    u.password_hash as drop_wrapped_key,
    fol.name as drop_folder_name
FROM files f
LEFT JOIN upload_tokens u ON f.drop_source_id = u.id
LEFT JOIN folders fol ON u.target_folder_id = fol.id
WHERE f.owner_id = $1
ORDER BY f.created_at DESC
`

type GetFilesWithDropSourceRow struct {
	ID                uuid.UUID
	Filename          string
	FilePath          string
	FileSize          int64
	Starred           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EncryptedMetadata sql.NullString
	DropSourceID      uuid.NullUUID
	DropToken         sql.NullString
	DropWrappedKey    sql.NullString
	DropFolderName    sql.NullString
}

func (q *Queries) GetFilesWithDropSource(ctx context.Context, ownerID uuid.NullUUID) ([]GetFilesWithDropSourceRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesWithDropSource, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesWithDropSourceRow
	for rows.Next() {
		var i GetFilesWithDropSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.Starred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptedMetadata,
			&i.DropSourceID,
			&i.DropToken,
			&i.DropWrappedKey,
			&i.DropFolderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
