// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_tags.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTagToFile = `-- name: AddTagToFile :one
INSERT INTO file_tags (file_id, tag_id, created_at)
VALUES ($1, $2, $3)
RETURNING file_id, tag_id, created_at
`

type AddTagToFileParams struct {
	FileID    uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) AddTagToFile(ctx context.Context, arg AddTagToFileParams) (FileTag, error) {
	row := q.db.QueryRowContext(ctx, addTagToFile, arg.FileID, arg.TagID, arg.CreatedAt)
	var i FileTag
	err := row.Scan(&i.FileID, &i.TagID, &i.CreatedAt)
	return i, err
}

const deleteFileTags = `-- name: DeleteFileTags :exec
DELETE FROM file_tags WHERE file_id = $1
`

func (q *Queries) DeleteFileTags(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileTags, fileID)
	return err
}

const deleteTagFromAllFiles = `-- name: DeleteTagFromAllFiles :exec
DELETE FROM file_tags WHERE tag_id = $1
`

func (q *Queries) DeleteTagFromAllFiles(ctx context.Context, tagID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTagFromAllFiles, tagID)
	return err
}

const getFileTags = `-- name: GetFileTags :many
SELECT t.id, t.owner_id, t.name, t.color, t.created_at FROM tags t
INNER JOIN file_tags ft ON t.id = ft.tag_id
WHERE ft.file_id = $1
`

func (q *Queries) GetFileTags(ctx context.Context, fileID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getFileTags, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesWithTag = `-- name: GetFilesWithTag :many
SELECT f.id, f.owner_id, f.filename, f.file_path, f.file_size, f.encrypted_metadata, f.current_key_version, f.created_at, f.updated_at, f.starred, f.drop_source_id FROM files f
INNER JOIN file_tags ft ON f.id = ft.file_id
WHERE ft.tag_id = $1 AND f.owner_id = $2
ORDER BY f.created_at DESC
`

type GetFilesWithTagParams struct {
	TagID   uuid.UUID
	OwnerID uuid.NullUUID
}

func (q *Queries) GetFilesWithTag(ctx context.Context, arg GetFilesWithTagParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesWithTag, arg.TagID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForFile = `-- name: GetTagsForFile :many
SELECT t.id, t.owner_id, t.name, t.color, t.created_at FROM tags t
INNER JOIN file_tags ft ON t.id = ft.tag_id
WHERE ft.file_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForFile(ctx context.Context, fileID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromFile = `-- name: RemoveTagFromFile :exec
DELETE FROM file_tags
WHERE file_id = $1 AND tag_id = $2
`

type RemoveTagFromFileParams struct {
	FileID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) RemoveTagFromFile(ctx context.Context, arg RemoveTagFromFileParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromFile, arg.FileID, arg.TagID)
	return err
}
