// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_access_keys.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFileAccessKey = `-- name: CreateFileAccessKey :one
INSERT INTO file_access_keys (file_id, user_id, wrapped_key)
VALUES ($1, $2, $3)
RETURNING id, file_id, user_id, wrapped_key, created_at
`

type CreateFileAccessKeyParams struct {
	FileID     uuid.NullUUID
	UserID     uuid.NullUUID
	WrappedKey string
}

func (q *Queries) CreateFileAccessKey(ctx context.Context, arg CreateFileAccessKeyParams) (FileAccessKey, error) {
	row := q.db.QueryRowContext(ctx, createFileAccessKey, arg.FileID, arg.UserID, arg.WrappedKey)
	var i FileAccessKey
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.WrappedKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileAccessKey = `-- name: DeleteFileAccessKey :exec
DELETE FROM file_access_keys
WHERE file_id = $1 AND user_id = $2
`

type DeleteFileAccessKeyParams struct {
	FileID uuid.NullUUID
	UserID uuid.NullUUID
}

func (q *Queries) DeleteFileAccessKey(ctx context.Context, arg DeleteFileAccessKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileAccessKey, arg.FileID, arg.UserID)
	return err
}

const getFileAccessKey = `-- name: GetFileAccessKey :one
SELECT id, file_id, user_id, wrapped_key, created_at FROM file_access_keys
WHERE file_id = $1 AND user_id = $2
`

type GetFileAccessKeyParams struct {
	FileID uuid.NullUUID
	UserID uuid.NullUUID
}

func (q *Queries) GetFileAccessKey(ctx context.Context, arg GetFileAccessKeyParams) (FileAccessKey, error) {
	row := q.db.QueryRowContext(ctx, getFileAccessKey, arg.FileID, arg.UserID)
	var i FileAccessKey
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.WrappedKey,
		&i.CreatedAt,
	)
	return i, err
}

const getFileAccessKeysByFile = `-- name: GetFileAccessKeysByFile :many
SELECT id, file_id, user_id, wrapped_key, created_at FROM file_access_keys
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileAccessKeysByFile(ctx context.Context, fileID uuid.NullUUID) ([]FileAccessKey, error) {
	rows, err := q.db.QueryContext(ctx, getFileAccessKeysByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAccessKey
	for rows.Next() {
		var i FileAccessKey
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.WrappedKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileAccessKeysByUser = `-- name: GetFileAccessKeysByUser :many
SELECT id, file_id, user_id, wrapped_key, created_at FROM file_access_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileAccessKeysByUser(ctx context.Context, userID uuid.NullUUID) ([]FileAccessKey, error) {
	rows, err := q.db.QueryContext(ctx, getFileAccessKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAccessKey
	for rows.Next() {
		var i FileAccessKey
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.WrappedKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
