// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_versions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFileVersion = `-- name: CreateFileVersion :one
INSERT INTO file_versions (
  file_id,
  version_number,
  file_size,
  encrypted_path,
  encryption_metadata,
  created_by,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, file_id, version_number, file_size, encrypted_path, encryption_metadata, created_by, created_at
`

type CreateFileVersionParams struct {
	FileID             uuid.UUID
	VersionNumber      int32
	FileSize           int64
	EncryptedPath      string
	EncryptionMetadata sql.NullString
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
}

func (q *Queries) CreateFileVersion(ctx context.Context, arg CreateFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRowContext(ctx, createFileVersion,
		arg.FileID,
		arg.VersionNumber,
		arg.FileSize,
		arg.EncryptedPath,
		arg.EncryptionMetadata,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.FileSize,
		&i.EncryptedPath,
		&i.EncryptionMetadata,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileVersion = `-- name: DeleteFileVersion :exec
DELETE FROM file_versions
WHERE id = $1
`

func (q *Queries) DeleteFileVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileVersion, id)
	return err
}

const deleteFileVersions = `-- name: DeleteFileVersions :exec
DELETE FROM file_versions WHERE file_id = $1
`

func (q *Queries) DeleteFileVersions(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileVersions, fileID)
	return err
}

const getFileVersionByID = `-- name: GetFileVersionByID :one
SELECT id, file_id, version_number, file_size, encrypted_path, encryption_metadata, created_by, created_at FROM file_versions
WHERE id = $1
`

func (q *Queries) GetFileVersionByID(ctx context.Context, id uuid.UUID) (FileVersion, error) {
	row := q.db.QueryRowContext(ctx, getFileVersionByID, id)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.FileSize,
		&i.EncryptedPath,
		&i.EncryptionMetadata,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getFileVersions = `-- name: GetFileVersions :many
SELECT id, file_id, version_number, file_size, encrypted_path, encryption_metadata, created_by, created_at FROM file_versions
WHERE file_id = $1
ORDER BY version_number DESC
`

func (q *Queries) GetFileVersions(ctx context.Context, fileID uuid.UUID) ([]FileVersion, error) {
	rows, err := q.db.QueryContext(ctx, getFileVersions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileVersion
	for rows.Next() {
		var i FileVersion
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.VersionNumber,
			&i.FileSize,
			&i.EncryptedPath,
			&i.EncryptionMetadata,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVersion = `-- name: GetLatestVersion :one
SELECT id, file_id, version_number, file_size, encrypted_path, encryption_metadata, created_by, created_at FROM file_versions
WHERE file_id = $1
ORDER BY version_number DESC
LIMIT 1
`

func (q *Queries) GetLatestVersion(ctx context.Context, fileID uuid.UUID) (FileVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersion, fileID)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.FileSize,
		&i.EncryptedPath,
		&i.EncryptionMetadata,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionCount = `-- name: GetVersionCount :one
SELECT COUNT(*) FROM file_versions
WHERE file_id = $1
`

func (q *Queries) GetVersionCount(ctx context.Context, fileID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVersionCount, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const restoreVersion = `-- name: RestoreVersion :one
SELECT id, file_id, version_number, file_size, encrypted_path, encryption_metadata, created_by, created_at FROM file_versions
WHERE file_id = $1 AND version_number = $2
`

type RestoreVersionParams struct {
	FileID        uuid.UUID
	VersionNumber int32
}

func (q *Queries) RestoreVersion(ctx context.Context, arg RestoreVersionParams) (FileVersion, error) {
	row := q.db.QueryRowContext(ctx, restoreVersion, arg.FileID, arg.VersionNumber)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.FileSize,
		&i.EncryptedPath,
		&i.EncryptionMetadata,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
