// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countFilesByOwnerID = `-- name: CountFilesByOwnerID :one
SELECT COUNT(*) FROM files
WHERE owner_id = $1
`

func (q *Queries) CountFilesByOwnerID(ctx context.Context, ownerID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesByOwnerID, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    owner_id,
    filename,
    file_path,
    file_size,
    encrypted_metadata,
    current_key_version,
    created_at,
    updated_at,
    drop_source_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id
`

type CreateFileParams struct {
	OwnerID           uuid.NullUUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DropSourceID      uuid.NullUUID
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.OwnerID,
		arg.Filename,
		arg.FilePath,
		arg.FileSize,
		arg.EncryptedMetadata,
		arg.CurrentKeyVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DropSourceID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedMetadata,
		&i.CurrentKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.DropSourceID,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteFilesByOwnerID = `-- name: DeleteFilesByOwnerID :exec
DELETE FROM files
WHERE owner_id = $1
`

func (q *Queries) DeleteFilesByOwnerID(ctx context.Context, ownerID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteFilesByOwnerID, ownerID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedMetadata,
		&i.CurrentKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.DropSourceID,
	)
	return i, err
}

const getFilesByOwnerID = `-- name: GetFilesByOwnerID :many
SELECT id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id FROM files
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFilesByOwnerID(ctx context.Context, ownerID uuid.NullUUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByOwnerIDWithPagination = `-- name: GetFilesByOwnerIDWithPagination :many
SELECT id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id FROM files
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetFilesByOwnerIDWithPaginationParams struct {
	OwnerID uuid.NullUUID
	Limit   int32
	Offset  int32
}

func (q *Queries) GetFilesByOwnerIDWithPagination(ctx context.Context, arg GetFilesByOwnerIDWithPaginationParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByOwnerIDWithPagination, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleFileStarred = `-- name: ToggleFileStarred :one
UPDATE files
SET starred = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id
`

type ToggleFileStarredParams struct {
	ID        uuid.UUID
	Starred   bool
	UpdatedAt time.Time
}

func (q *Queries) ToggleFileStarred(ctx context.Context, arg ToggleFileStarredParams) (File, error) {
	row := q.db.QueryRowContext(ctx, toggleFileStarred, arg.ID, arg.Starred, arg.UpdatedAt)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedMetadata,
		&i.CurrentKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.DropSourceID,
	)
	return i, err
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET 
    filename = $2,
    file_path = $3,
    file_size = $4,
    encrypted_metadata = $5,
    current_key_version = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id
`

type UpdateFileParams struct {
	ID                uuid.UUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	UpdatedAt         time.Time
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFile,
		arg.ID,
		arg.Filename,
		arg.FilePath,
		arg.FileSize,
		arg.EncryptedMetadata,
		arg.CurrentKeyVersion,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedMetadata,
		&i.CurrentKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.DropSourceID,
	)
	return i, err
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
UPDATE files
SET 
    encrypted_metadata = $2,
    current_key_version = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, owner_id, filename, file_path, file_size, encrypted_metadata, current_key_version, created_at, updated_at, starred, drop_source_id
`

type UpdateFileMetadataParams struct {
	ID                uuid.UUID
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	UpdatedAt         time.Time
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileMetadata,
		arg.ID,
		arg.EncryptedMetadata,
		arg.CurrentKeyVersion,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedMetadata,
		&i.CurrentKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.DropSourceID,
	)
	return i, err
}
