// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
  owner_id,
  name,
  parent_id,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, parent_id, created_at, updated_at
`

type CreateFolderParams struct {
	OwnerID   uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder,
		arg.OwnerID,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders
WHERE id = $1 AND owner_id = $2
`

type DeleteFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, arg.ID, arg.OwnerID)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, owner_id, name, parent_id, created_at, updated_at FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderPath = `-- name: GetFolderPath :many
WITH RECURSIVE folder_path AS (
  SELECT folders.id, folders.name, folders.parent_id, 0 as level
  FROM folders
  WHERE folders.id = $1
  
  UNION ALL
  
  SELECT f.id, f.name, f.parent_id, fp.level + 1
  FROM folders f
  INNER JOIN folder_path fp ON f.id = fp.parent_id
)
SELECT folder_path.id, folder_path.name, folder_path.parent_id, folder_path.level
FROM folder_path
ORDER BY level DESC
`

type GetFolderPathRow struct {
	ID       uuid.UUID
	Name     string
	ParentID uuid.NullUUID
	Level    int32
}

func (q *Queries) GetFolderPath(ctx context.Context, id uuid.UUID) ([]GetFolderPathRow, error) {
	rows, err := q.db.QueryContext(ctx, getFolderPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFolderPathRow
	for rows.Next() {
		var i GetFolderPathRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersByOwner = `-- name: GetFoldersByOwner :many
SELECT id, owner_id, name, parent_id, created_at, updated_at FROM folders
WHERE owner_id = $1
ORDER BY name ASC
`

func (q *Queries) GetFoldersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, getFoldersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersByParent = `-- name: GetFoldersByParent :many
SELECT id, owner_id, name, parent_id, created_at, updated_at FROM folders
WHERE owner_id = $1 AND parent_id = $2
ORDER BY name ASC
`

type GetFoldersByParentParams struct {
	OwnerID  uuid.UUID
	ParentID uuid.NullUUID
}

func (q *Queries) GetFoldersByParent(ctx context.Context, arg GetFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, getFoldersByParent, arg.OwnerID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootFolders = `-- name: GetRootFolders :many
SELECT id, owner_id, name, parent_id, created_at, updated_at FROM folders
WHERE owner_id = $1 AND parent_id IS NULL
ORDER BY name ASC
`

func (q *Queries) GetRootFolders(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, getRootFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name = $2, parent_id = $3, updated_at = $4
WHERE id = $1 AND owner_id = $5
RETURNING id, owner_id, name, parent_id, created_at, updated_at
`

type UpdateFolderParams struct {
	ID        uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolder,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.UpdatedAt,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
