// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_share_links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFolderShareFileKey = `-- name: CreateFolderShareFileKey :exec
INSERT INTO folder_share_file_keys (folder_share_link_id, file_id, wrapped_file_key)
VALUES ($1, $2, $3)
`

type CreateFolderShareFileKeyParams struct {
	FolderShareLinkID uuid.UUID
	FileID            uuid.UUID
	WrappedFileKey    string
}

func (q *Queries) CreateFolderShareFileKey(ctx context.Context, arg CreateFolderShareFileKeyParams) error {
	_, err := q.db.ExecContext(ctx, createFolderShareFileKey, arg.FolderShareLinkID, arg.FileID, arg.WrappedFileKey)
	return err
}

const createFolderShareLink = `-- name: CreateFolderShareLink :one
INSERT INTO folder_share_links (folder_id, owner_id, token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, folder_id, owner_id, token, expires_at, is_active, access_count, last_accessed_at, created_at
`

type CreateFolderShareLinkParams struct {
	FolderID  uuid.UUID
	OwnerID   uuid.UUID
	Token     string
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateFolderShareLink(ctx context.Context, arg CreateFolderShareLinkParams) (FolderShareLink, error) {
	row := q.db.QueryRowContext(ctx, createFolderShareLink,
		arg.FolderID,
		arg.OwnerID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i FolderShareLink
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.OwnerID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFolderShareFileKeyByFile = `-- name: GetFolderShareFileKeyByFile :one
SELECT id, folder_share_link_id, file_id, wrapped_file_key, created_at FROM folder_share_file_keys
WHERE folder_share_link_id = $1 AND file_id = $2
`

type GetFolderShareFileKeyByFileParams struct {
	FolderShareLinkID uuid.UUID
	FileID            uuid.UUID
}

func (q *Queries) GetFolderShareFileKeyByFile(ctx context.Context, arg GetFolderShareFileKeyByFileParams) (FolderShareFileKey, error) {
	row := q.db.QueryRowContext(ctx, getFolderShareFileKeyByFile, arg.FolderShareLinkID, arg.FileID)
	var i FolderShareFileKey
	err := row.Scan(
		&i.ID,
		&i.FolderShareLinkID,
		&i.FileID,
		&i.WrappedFileKey,
		&i.CreatedAt,
	)
	return i, err
}

const getFolderShareFileKeys = `-- name: GetFolderShareFileKeys :many
SELECT id, folder_share_link_id, file_id, wrapped_file_key, created_at FROM folder_share_file_keys
WHERE folder_share_link_id = $1
`

func (q *Queries) GetFolderShareFileKeys(ctx context.Context, folderShareLinkID uuid.UUID) ([]FolderShareFileKey, error) {
	rows, err := q.db.QueryContext(ctx, getFolderShareFileKeys, folderShareLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderShareFileKey
	for rows.Next() {
		var i FolderShareFileKey
		if err := rows.Scan(
			&i.ID,
			&i.FolderShareLinkID,
			&i.FileID,
			&i.WrappedFileKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderShareLinkByToken = `-- name: GetFolderShareLinkByToken :one
SELECT id, folder_id, owner_id, token, expires_at, is_active, access_count, last_accessed_at, created_at FROM folder_share_links
WHERE token = $1 AND is_active = TRUE
`

func (q *Queries) GetFolderShareLinkByToken(ctx context.Context, token string) (FolderShareLink, error) {
	row := q.db.QueryRowContext(ctx, getFolderShareLinkByToken, token)
	var i FolderShareLink
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.OwnerID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementFolderShareLinkAccess = `-- name: IncrementFolderShareLinkAccess :exec
UPDATE folder_share_links
SET access_count = access_count + 1, last_accessed_at = NOW()
WHERE token = $1
`

func (q *Queries) IncrementFolderShareLinkAccess(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, incrementFolderShareLinkAccess, token)
	return err
}

const listFolderShareLinksByFolder = `-- name: ListFolderShareLinksByFolder :many
SELECT id, folder_id, owner_id, token, expires_at, is_active, access_count, last_accessed_at, created_at FROM folder_share_links
WHERE folder_id = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListFolderShareLinksByFolderParams struct {
	FolderID uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) ListFolderShareLinksByFolder(ctx context.Context, arg ListFolderShareLinksByFolderParams) ([]FolderShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listFolderShareLinksByFolder, arg.FolderID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderShareLink
	for rows.Next() {
		var i FolderShareLink
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.OwnerID,
			&i.Token,
			&i.ExpiresAt,
			&i.IsActive,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderShareLinksByOwner = `-- name: ListFolderShareLinksByOwner :many
SELECT id, folder_id, owner_id, token, expires_at, is_active, access_count, last_accessed_at, created_at FROM folder_share_links
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFolderShareLinksByOwner(ctx context.Context, ownerID uuid.UUID) ([]FolderShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listFolderShareLinksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderShareLink
	for rows.Next() {
		var i FolderShareLink
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.OwnerID,
			&i.Token,
			&i.ExpiresAt,
			&i.IsActive,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFolderShareLink = `-- name: RevokeFolderShareLink :exec
UPDATE folder_share_links
SET is_active = FALSE
WHERE id = $1 AND owner_id = $2
`

type RevokeFolderShareLinkParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RevokeFolderShareLink(ctx context.Context, arg RevokeFolderShareLinkParams) error {
	_, err := q.db.ExecContext(ctx, revokeFolderShareLink, arg.ID, arg.OwnerID)
	return err
}
