// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_shares.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFolderShare = `-- name: CreateFolderShare :one
INSERT INTO folder_shares (folder_id, user_id, wrapped_key, shared_by, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, folder_id, user_id, wrapped_key, shared_by, created_at
`

type CreateFolderShareParams struct {
	FolderID   uuid.UUID
	UserID     uuid.UUID
	WrappedKey string
	SharedBy   uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) CreateFolderShare(ctx context.Context, arg CreateFolderShareParams) (FolderShare, error) {
	row := q.db.QueryRowContext(ctx, createFolderShare,
		arg.FolderID,
		arg.UserID,
		arg.WrappedKey,
		arg.SharedBy,
		arg.CreatedAt,
	)
	var i FolderShare
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.WrappedKey,
		&i.SharedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolderShare = `-- name: DeleteFolderShare :exec
DELETE FROM folder_shares
WHERE folder_id = $1 AND user_id = $2
`

type DeleteFolderShareParams struct {
	FolderID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteFolderShare(ctx context.Context, arg DeleteFolderShareParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolderShare, arg.FolderID, arg.UserID)
	return err
}

const getFolderShare = `-- name: GetFolderShare :one
SELECT id, folder_id, user_id, wrapped_key, shared_by, created_at FROM folder_shares
WHERE folder_id = $1 AND user_id = $2
`

type GetFolderShareParams struct {
	FolderID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetFolderShare(ctx context.Context, arg GetFolderShareParams) (FolderShare, error) {
	row := q.db.QueryRowContext(ctx, getFolderShare, arg.FolderID, arg.UserID)
	var i FolderShare
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.WrappedKey,
		&i.SharedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listFolderSharesForFolder = `-- name: ListFolderSharesForFolder :many
SELECT id, folder_id, user_id, wrapped_key, shared_by, created_at FROM folder_shares
WHERE folder_id = $1
`

func (q *Queries) ListFolderSharesForFolder(ctx context.Context, folderID uuid.UUID) ([]FolderShare, error) {
	rows, err := q.db.QueryContext(ctx, listFolderSharesForFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderShare
	for rows.Next() {
		var i FolderShare
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.WrappedKey,
			&i.SharedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersSharedWithUser = `-- name: ListFoldersSharedWithUser :many
SELECT f.id, f.owner_id, f.name, f.parent_id, f.created_at, f.updated_at, fs.wrapped_key, fs.shared_by, fs.created_at as shared_at FROM folders f
INNER JOIN folder_shares fs ON f.id = fs.folder_id
WHERE fs.user_id = $1
ORDER BY fs.created_at DESC
`

type ListFoldersSharedWithUserRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	Name       string
	ParentID   uuid.NullUUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	WrappedKey string
	SharedBy   uuid.UUID
	SharedAt   time.Time
}

func (q *Queries) ListFoldersSharedWithUser(ctx context.Context, userID uuid.UUID) ([]ListFoldersSharedWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersSharedWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoldersSharedWithUserRow
	for rows.Next() {
		var i ListFoldersSharedWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WrappedKey,
			&i.SharedBy,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
