// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role, created_at
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    sql.NullString
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (user_id, name, description, updated_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, user_id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.UserID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND user_id = $2
`

type DeleteGroupParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.ID, arg.UserID)
	return err
}

const getFilesSharedViaGroups = `-- name: GetFilesSharedViaGroups :many
SELECT DISTINCT f.id, f.owner_id, f.filename, f.file_path, f.file_size, f.encrypted_metadata, f.current_key_version, f.created_at, f.updated_at, f.starred, f.drop_source_id,
       g.name as group_name,
       g.id as group_id,
       gfs.created_at as shared_at,
       owner.email as owner_email,
       owner.first_name as owner_first_name,
       owner.last_name as owner_last_name,
       sharer.email as shared_by_email,
       sharer.first_name as shared_by_first_name,
       sharer.last_name as shared_by_last_name
FROM group_file_shares gfs
JOIN files f ON gfs.file_id = f.id
JOIN groups g ON gfs.group_id = g.id
JOIN group_members gm ON gfs.group_id = gm.group_id
JOIN users owner ON f.owner_id = owner.id
JOIN users sharer ON gfs.created_by = sharer.id
WHERE gm.user_id = $1
ORDER BY gfs.created_at DESC
`

type GetFilesSharedViaGroupsRow struct {
	ID                uuid.UUID
	OwnerID           uuid.NullUUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Starred           bool
	DropSourceID      uuid.NullUUID
	GroupName         string
	GroupID           uuid.UUID
	SharedAt          sql.NullTime
	OwnerEmail        string
	OwnerFirstName    string
	OwnerLastName     string
	SharedByEmail     string
	SharedByFirstName string
	SharedByLastName  string
}

func (q *Queries) GetFilesSharedViaGroups(ctx context.Context, userID uuid.UUID) ([]GetFilesSharedViaGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedViaGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesSharedViaGroupsRow
	for rows.Next() {
		var i GetFilesSharedViaGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
			&i.GroupName,
			&i.GroupID,
			&i.SharedAt,
			&i.OwnerEmail,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.SharedByEmail,
			&i.SharedByFirstName,
			&i.SharedByLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT g.id, g.user_id, g.name, g.description, g.created_at, g.updated_at, 
       (SELECT COUNT(*) FROM group_members WHERE group_id = g.id) as member_count,
       (SELECT COUNT(*) FROM group_file_shares WHERE group_id = g.id) as file_count
FROM groups g
WHERE g.id = $1
`

type GetGroupByIDRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	MemberCount int64
	FileCount   int64
}

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberCount,
		&i.FileCount,
	)
	return i, err
}

const getGroupFiles = `-- name: GetGroupFiles :many
SELECT f.id, f.owner_id, f.filename, f.file_path, f.file_size, f.encrypted_metadata, f.current_key_version, f.created_at, f.updated_at, f.starred, f.drop_source_id,
       gfs.created_at as shared_at,
       u.username as shared_by,
       f.encrypted_metadata
FROM group_file_shares gfs
JOIN files f ON gfs.file_id = f.id
JOIN users u ON gfs.created_by = u.id
WHERE gfs.group_id = $1
ORDER BY gfs.created_at DESC
`

type GetGroupFilesRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.NullUUID
	Filename            string
	FilePath            string
	FileSize            int64
	EncryptedMetadata   sql.NullString
	CurrentKeyVersion   sql.NullInt32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Starred             bool
	DropSourceID        uuid.NullUUID
	SharedAt            sql.NullTime
	SharedBy            string
	EncryptedMetadata_2 sql.NullString
}

func (q *Queries) GetGroupFiles(ctx context.Context, groupID uuid.UUID) ([]GetGroupFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupFiles, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupFilesRow
	for rows.Next() {
		var i GetGroupFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
			&i.SharedAt,
			&i.SharedBy,
			&i.EncryptedMetadata_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.created_at, 
       u.username, u.email, u.first_name, u.last_name
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
ORDER BY gm.created_at
`

type GetGroupMembersRow struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	Role      sql.NullString
	CreatedAt sql.NullTime
	Username  string
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupWrappedKeyForUser = `-- name: GetGroupWrappedKeyForUser :one
SELECT gfs.wrapped_key
FROM group_file_shares gfs
JOIN group_members gm ON gfs.group_id = gm.group_id
WHERE gfs.file_id = $1
  AND gm.user_id = $2
LIMIT 1
`

type GetGroupWrappedKeyForUserParams struct {
	FileID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGroupWrappedKeyForUser(ctx context.Context, arg GetGroupWrappedKeyForUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupWrappedKeyForUser, arg.FileID, arg.UserID)
	var wrapped_key string
	err := row.Scan(&wrapped_key)
	return wrapped_key, err
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT g.id, g.user_id, g.name, g.description, g.created_at, g.updated_at,
       (SELECT COUNT(*) FROM group_members WHERE group_id = g.id) as member_count,
       (SELECT COUNT(*) FROM group_file_shares WHERE group_id = g.id) as file_count
FROM groups g
WHERE g.user_id = $1
ORDER BY g.created_at DESC
`

type GetGroupsByUserIDRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	MemberCount int64
	FileCount   int64
}

func (q *Queries) GetGroupsByUserID(ctx context.Context, userID uuid.UUID) ([]GetGroupsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByUserIDRow
	for rows.Next() {
		var i GetGroupsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsForUser = `-- name: GetGroupsForUser :many
SELECT g.id, g.user_id, g.name, g.description, g.created_at, g.updated_at,
       gm.role,
       (SELECT COUNT(*) FROM group_members WHERE group_id = g.id) as member_count,
       (SELECT COUNT(*) FROM group_file_shares WHERE group_id = g.id) as file_count
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type GetGroupsForUserRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Role        sql.NullString
	MemberCount int64
	FileCount   int64
}

func (q *Queries) GetGroupsForUser(ctx context.Context, userID uuid.UUID) ([]GetGroupsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsForUserRow
	for rows.Next() {
		var i GetGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MemberCount,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsOwner = `-- name: GetGroupsOwner :many
SELECT id, user_id, name, description, created_at, updated_at FROM groups WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGroupsOwner(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT 1 as is_member
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type IsUserInGroupParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, isUserInGroup, arg.GroupID, arg.UserID)
	var is_member int32
	err := row.Scan(&is_member)
	return is_member, err
}

const removeFileFromGroup = `-- name: RemoveFileFromGroup :exec
DELETE FROM group_file_shares 
WHERE group_id = $1 AND file_id = $2
`

type RemoveFileFromGroupParams struct {
	GroupID uuid.UUID
	FileID  uuid.UUID
}

func (q *Queries) RemoveFileFromGroup(ctx context.Context, arg RemoveFileFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeFileFromGroup, arg.GroupID, arg.FileID)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members 
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const shareFileToGroup = `-- name: ShareFileToGroup :one
INSERT INTO group_file_shares (group_id, file_id, wrapped_key, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, file_id, wrapped_key, created_at, created_by
`

type ShareFileToGroupParams struct {
	GroupID    uuid.UUID
	FileID     uuid.UUID
	WrappedKey string
	CreatedBy  uuid.UUID
}

func (q *Queries) ShareFileToGroup(ctx context.Context, arg ShareFileToGroupParams) (GroupFileShare, error) {
	row := q.db.QueryRowContext(ctx, shareFileToGroup,
		arg.GroupID,
		arg.FileID,
		arg.WrappedKey,
		arg.CreatedBy,
	)
	var i GroupFileShare
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FileID,
		&i.WrappedKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups 
SET name = COALESCE($3, name),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        sql.NullString
	Description sql.NullString
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
