// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActivityLog struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	EventType string
	Payload   pqtype.NullRawMessage
	CreatedAt time.Time
}

type AuditLog struct {
	ID           uuid.UUID
	UserID       uuid.NullUUID
	Action       string
	ResourceType string
	ResourceID   uuid.NullUUID
	Metadata     pqtype.NullRawMessage
	IpAddress    pqtype.Inet
	CreatedAt    time.Time
}

type EmailAccount struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Email                 string
	ImapHost              string
	ImapPort              int32
	ImapUser              string
	EncryptedImapPassword []byte
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type File struct {
	ID                uuid.UUID
	OwnerID           uuid.NullUUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Starred           bool
	DropSourceID      uuid.NullUUID
}

type FileAccessKey struct {
	ID         uuid.UUID
	FileID     uuid.NullUUID
	UserID     uuid.NullUUID
	WrappedKey string
	CreatedAt  sql.NullTime
}

type FileRequest struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Token         string
	Description   sql.NullString
	ExpiresAt     sql.NullTime
	MaxFileSize   sql.NullInt64
	IsActive      sql.NullBool
	UploadedFiles pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type FileShare struct {
	ID               uuid.UUID
	FileID           uuid.NullUUID
	SharedWithUserID uuid.NullUUID
	WrappedKey       string
	CreatedAt        time.Time
}

type FileTag struct {
	FileID    uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
}

type FileVersion struct {
	ID                 uuid.UUID
	FileID             uuid.UUID
	VersionNumber      int32
	FileSize           int64
	EncryptedPath      string
	EncryptionMetadata sql.NullString
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
}

type Folder struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Group struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GroupFileShare struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	FileID     uuid.UUID
	WrappedKey string
	CreatedAt  sql.NullTime
	CreatedBy  uuid.UUID
}

type GroupMember struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	Role      sql.NullString
	CreatedAt sql.NullTime
}

type PluginsManifest struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Version   string
	Manifest  json.RawMessage
	IsEnabled sql.NullBool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PublicShareLink struct {
	ID             uuid.UUID
	FileID         uuid.UUID
	OwnerID        uuid.UUID
	Token          string
	ExpiresAt      sql.NullTime
	IsActive       bool
	CreatedAt      time.Time
	AccessCount    int32
	LastAccessedAt sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	RevokedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type SecureNote struct {
	ID                 uuid.UUID
	OwnerID            uuid.UUID
	Title              string
	EncryptedContent   string
	EncryptionMetadata string
	IsLocked           sql.NullBool
	LastAccessedAt     sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Tag struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Color     sql.NullString
	CreatedAt time.Time
}

type UploadToken struct {
	ID              uuid.UUID
	Token           string
	OwnerUserID     uuid.UUID
	TargetFolderID  uuid.UUID
	ExpiresAt       sql.NullTime
	MaxFiles        sql.NullInt32
	FilesUploaded   sql.NullInt32
	Used            sql.NullBool
	CreatedAt       sql.NullTime
	PasswordHash    sql.NullString
	LinkName        sql.NullString
	PinWrappedKey   sql.NullString
	Description     sql.NullString
	ClientMessage   sql.NullString
	SealAfterUpload bool
	LastUsedAt      sql.NullTime
}

type User struct {
	ID                     uuid.UUID
	FirstName              string
	LastName               string
	Username               string
	Email                  string
	PasswordHash           string
	PublicKey              string
	PrivateKeyEncrypted    string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	IsAdmin                sql.NullBool
	PinHash                sql.NullString
	PinSetAt               sql.NullTime
	PrivateKeyPinEncrypted sql.NullString
	PinFailedAttempts      int32
	PinLockedUntil         sql.NullTime
	OrganizationName       sql.NullString
}
