// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins_manifest.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM plugins_manifest
WHERE id = $1 AND owner_id = $2
`

type DeletePluginParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeletePlugin(ctx context.Context, arg DeletePluginParams) error {
	_, err := q.db.ExecContext(ctx, deletePlugin, arg.ID, arg.OwnerID)
	return err
}

const disablePlugin = `-- name: DisablePlugin :one
UPDATE plugins_manifest
SET is_enabled = false,
    updated_at = $2
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, name, version, manifest, is_enabled, created_at, updated_at
`

type DisablePluginParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) DisablePlugin(ctx context.Context, arg DisablePluginParams) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, disablePlugin, arg.ID, arg.UpdatedAt, arg.OwnerID)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enablePlugin = `-- name: EnablePlugin :one
UPDATE plugins_manifest
SET is_enabled = true,
    updated_at = $2
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, name, version, manifest, is_enabled, created_at, updated_at
`

type EnablePluginParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) EnablePlugin(ctx context.Context, arg EnablePluginParams) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, enablePlugin, arg.ID, arg.UpdatedAt, arg.OwnerID)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledPlugins = `-- name: GetEnabledPlugins :many
SELECT id, owner_id, name, version, manifest, is_enabled, created_at, updated_at FROM plugins_manifest
WHERE owner_id = $1 AND is_enabled = true
ORDER BY name ASC
`

func (q *Queries) GetEnabledPlugins(ctx context.Context, ownerID uuid.UUID) ([]PluginsManifest, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledPlugins, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginsManifest
	for rows.Next() {
		var i PluginsManifest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Version,
			&i.Manifest,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPluginByID = `-- name: GetPluginByID :one
SELECT id, owner_id, name, version, manifest, is_enabled, created_at, updated_at FROM plugins_manifest
WHERE id = $1
`

func (q *Queries) GetPluginByID(ctx context.Context, id uuid.UUID) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, getPluginByID, id)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginByNameVersion = `-- name: GetPluginByNameVersion :one
SELECT id, owner_id, name, version, manifest, is_enabled, created_at, updated_at FROM plugins_manifest
WHERE owner_id = $1 AND name = $2 AND version = $3
`

type GetPluginByNameVersionParams struct {
	OwnerID uuid.UUID
	Name    string
	Version string
}

func (q *Queries) GetPluginByNameVersion(ctx context.Context, arg GetPluginByNameVersionParams) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, getPluginByNameVersion, arg.OwnerID, arg.Name, arg.Version)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginsByOwner = `-- name: GetPluginsByOwner :many
SELECT id, owner_id, name, version, manifest, is_enabled, created_at, updated_at FROM plugins_manifest
WHERE owner_id = $1
ORDER BY name ASC
`

func (q *Queries) GetPluginsByOwner(ctx context.Context, ownerID uuid.UUID) ([]PluginsManifest, error) {
	rows, err := q.db.QueryContext(ctx, getPluginsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginsManifest
	for rows.Next() {
		var i PluginsManifest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Version,
			&i.Manifest,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPlugin = `-- name: RegisterPlugin :one
INSERT INTO plugins_manifest (
  owner_id,
  name,
  version,
  manifest,
  is_enabled,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, name, version, manifest, is_enabled, created_at, updated_at
`

type RegisterPluginParams struct {
	OwnerID   uuid.UUID
	Name      string
	Version   string
	Manifest  json.RawMessage
	IsEnabled sql.NullBool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) RegisterPlugin(ctx context.Context, arg RegisterPluginParams) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, registerPlugin,
		arg.OwnerID,
		arg.Name,
		arg.Version,
		arg.Manifest,
		arg.IsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlugin = `-- name: UpdatePlugin :one
UPDATE plugins_manifest
SET manifest = $2,
    is_enabled = $3,
    updated_at = $4
WHERE id = $1 AND owner_id = $5
RETURNING id, owner_id, name, version, manifest, is_enabled, created_at, updated_at
`

type UpdatePluginParams struct {
	ID        uuid.UUID
	Manifest  json.RawMessage
	IsEnabled sql.NullBool
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) UpdatePlugin(ctx context.Context, arg UpdatePluginParams) (PluginsManifest, error) {
	row := q.db.QueryRowContext(ctx, updatePlugin,
		arg.ID,
		arg.Manifest,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.OwnerID,
	)
	var i PluginsManifest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.Manifest,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
