// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public_share_links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPublicShareLink = `-- name: CreatePublicShareLink :one
INSERT INTO public_share_links (file_id, owner_id, token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, file_id, owner_id, token, expires_at, is_active, created_at
`

type CreatePublicShareLinkParams struct {
	FileID    uuid.UUID
	OwnerID   uuid.UUID
	Token     string
	ExpiresAt sql.NullTime
}

func (q *Queries) CreatePublicShareLink(ctx context.Context, arg CreatePublicShareLinkParams) (PublicShareLink, error) {
	row := q.db.QueryRowContext(ctx, createPublicShareLink,
		arg.FileID,
		arg.OwnerID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicShareLinkByToken = `-- name: GetPublicShareLinkByToken :one
SELECT id, file_id, owner_id, token, expires_at, is_active, created_at FROM public_share_links
WHERE token = $1 AND is_active = TRUE
`

func (q *Queries) GetPublicShareLinkByToken(ctx context.Context, token string) (PublicShareLink, error) {
	row := q.db.QueryRowContext(ctx, getPublicShareLinkByToken, token)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicShareLinksByOwner = `-- name: ListPublicShareLinksByOwner :many
SELECT id, file_id, owner_id, token, expires_at, is_active, created_at FROM public_share_links
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPublicShareLinksByOwner(ctx context.Context, ownerID uuid.UUID) ([]PublicShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listPublicShareLinksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicShareLink
	for rows.Next() {
		var i PublicShareLink
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.OwnerID,
			&i.Token,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePublicShareLink = `-- name: RevokePublicShareLink :exec
UPDATE public_share_links
SET is_active = FALSE
WHERE id = $1 AND owner_id = $2
`

type RevokePublicShareLinkParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RevokePublicShareLink(ctx context.Context, arg RevokePublicShareLinkParams) error {
	_, err := q.db.ExecContext(ctx, revokePublicShareLink, arg.ID, arg.OwnerID)
	return err
}
