// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveRecoveryShare = `-- name: ApproveRecoveryShare :one
UPDATE account_recovery_shares
SET 
  status = 'approved',
  decrypted_share_part = $3,
  updated_at = $4
WHERE user_id = $1 AND custodian_id = $2
RETURNING id, user_id, custodian_id, wrapped_share_payload, status, decrypted_share_part, created_at, updated_at
`

type ApproveRecoveryShareParams struct {
	UserID             uuid.UUID
	CustodianID        uuid.UUID
	DecryptedSharePart sql.NullString
	UpdatedAt          time.Time
}

func (q *Queries) ApproveRecoveryShare(ctx context.Context, arg ApproveRecoveryShareParams) (AccountRecoveryShare, error) {
	row := q.db.QueryRowContext(ctx, approveRecoveryShare,
		arg.UserID,
		arg.CustodianID,
		arg.DecryptedSharePart,
		arg.UpdatedAt,
	)
	var i AccountRecoveryShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustodianID,
		&i.WrappedSharePayload,
		&i.Status,
		&i.DecryptedSharePart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateRecoveryShare = `-- name: CreateOrUpdateRecoveryShare :one
INSERT INTO account_recovery_shares (
  user_id,
  custodian_id,
  wrapped_share_payload,
  status,
  decrypted_share_part,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, custodian_id)
DO UPDATE SET
  wrapped_share_payload = EXCLUDED.wrapped_share_payload,
  status = EXCLUDED.status,
  decrypted_share_part = EXCLUDED.decrypted_share_part,
  updated_at = EXCLUDED.updated_at
RETURNING id, user_id, custodian_id, wrapped_share_payload, status, decrypted_share_part, created_at, updated_at
`

type CreateOrUpdateRecoveryShareParams struct {
	UserID              uuid.UUID
	CustodianID         uuid.UUID
	WrappedSharePayload string
	Status              string
	DecryptedSharePart  sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateOrUpdateRecoveryShare(ctx context.Context, arg CreateOrUpdateRecoveryShareParams) (AccountRecoveryShare, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateRecoveryShare,
		arg.UserID,
		arg.CustodianID,
		arg.WrappedSharePayload,
		arg.Status,
		arg.DecryptedSharePart,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AccountRecoveryShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustodianID,
		&i.WrappedSharePayload,
		&i.Status,
		&i.DecryptedSharePart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecoverySharesForUser = `-- name: DeleteRecoverySharesForUser :exec
DELETE FROM account_recovery_shares
WHERE user_id = $1
`

func (q *Queries) DeleteRecoverySharesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecoverySharesForUser, userID)
	return err
}

const getRecoveryRequestsForCustodian = `-- name: GetRecoveryRequestsForCustodian :many
SELECT 
  s.id, s.user_id, s.custodian_id, s.wrapped_share_payload, s.status, s.decrypted_share_part, s.created_at, s.updated_at,
  u.username AS owner_username,
  u.email AS owner_email,
  u.first_name AS owner_first_name,
  u.last_name AS owner_last_name
FROM account_recovery_shares s
JOIN users u ON s.user_id = u.id
WHERE s.custodian_id = $1 AND s.status = 'pending'
`

type GetRecoveryRequestsForCustodianRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	CustodianID         uuid.UUID
	WrappedSharePayload string
	Status              string
	DecryptedSharePart  sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OwnerUsername       string
	OwnerEmail          string
	OwnerFirstName      string
	OwnerLastName       string
}

func (q *Queries) GetRecoveryRequestsForCustodian(ctx context.Context, custodianID uuid.UUID) ([]GetRecoveryRequestsForCustodianRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecoveryRequestsForCustodian, custodianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecoveryRequestsForCustodianRow
	for rows.Next() {
		var i GetRecoveryRequestsForCustodianRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustodianID,
			&i.WrappedSharePayload,
			&i.Status,
			&i.DecryptedSharePart,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerEmail,
			&i.OwnerFirstName,
			&i.OwnerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecoverySharesForUser = `-- name: GetRecoverySharesForUser :many
SELECT id, user_id, custodian_id, wrapped_share_payload, status, decrypted_share_part, created_at, updated_at FROM account_recovery_shares
WHERE user_id = $1
`

func (q *Queries) GetRecoverySharesForUser(ctx context.Context, userID uuid.UUID) ([]AccountRecoveryShare, error) {
	rows, err := q.db.QueryContext(ctx, getRecoverySharesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountRecoveryShare
	for rows.Next() {
		var i AccountRecoveryShare
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustodianID,
			&i.WrappedSharePayload,
			&i.Status,
			&i.DecryptedSharePart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecoverySharesForUserWithCustodian = `-- name: GetRecoverySharesForUserWithCustodian :many
SELECT 
  s.id, s.user_id, s.custodian_id, s.wrapped_share_payload, s.status, s.decrypted_share_part, s.created_at, s.updated_at,
  u.username AS custodian_username,
  u.email AS custodian_email,
  u.first_name AS custodian_first_name,
  u.last_name AS custodian_last_name
FROM account_recovery_shares s
JOIN users u ON s.custodian_id = u.id
WHERE s.user_id = $1
`

type GetRecoverySharesForUserWithCustodianRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	CustodianID         uuid.UUID
	WrappedSharePayload string
	Status              string
	DecryptedSharePart  sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CustodianUsername   string
	CustodianEmail      string
	CustodianFirstName  string
	CustodianLastName   string
}

func (q *Queries) GetRecoverySharesForUserWithCustodian(ctx context.Context, userID uuid.UUID) ([]GetRecoverySharesForUserWithCustodianRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecoverySharesForUserWithCustodian, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecoverySharesForUserWithCustodianRow
	for rows.Next() {
		var i GetRecoverySharesForUserWithCustodianRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustodianID,
			&i.WrappedSharePayload,
			&i.Status,
			&i.DecryptedSharePart,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustodianUsername,
			&i.CustodianEmail,
			&i.CustodianFirstName,
			&i.CustodianLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startRecoveryRequestForUser = `-- name: StartRecoveryRequestForUser :exec
UPDATE account_recovery_shares
SET 
  status = 'pending',
  decrypted_share_part = NULL,
  updated_at = $2
WHERE user_id = $1
`

type StartRecoveryRequestForUserParams struct {
	UserID    uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) StartRecoveryRequestForUser(ctx context.Context, arg StartRecoveryRequestForUserParams) error {
	_, err := q.db.ExecContext(ctx, startRecoveryRequestForUser, arg.UserID, arg.UpdatedAt)
	return err
}
