// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secure_notes.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSecureNote = `-- name: CreateSecureNote :one
INSERT INTO secure_notes (
  owner_id,
  title,
  encrypted_content,
  encryption_metadata,
  is_locked,
  last_accessed_at,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at
`

type CreateSecureNoteParams struct {
	OwnerID            uuid.UUID
	Title              string
	EncryptedContent   string
	EncryptionMetadata string
	IsLocked           sql.NullBool
	LastAccessedAt     sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateSecureNote(ctx context.Context, arg CreateSecureNoteParams) (SecureNote, error) {
	row := q.db.QueryRowContext(ctx, createSecureNote,
		arg.OwnerID,
		arg.Title,
		arg.EncryptedContent,
		arg.EncryptionMetadata,
		arg.IsLocked,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SecureNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.EncryptedContent,
		&i.EncryptionMetadata,
		&i.IsLocked,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecureNote = `-- name: DeleteSecureNote :exec
DELETE FROM secure_notes
WHERE id = $1 AND owner_id = $2
`

type DeleteSecureNoteParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteSecureNote(ctx context.Context, arg DeleteSecureNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecureNote, arg.ID, arg.OwnerID)
	return err
}

const getSecureNoteByID = `-- name: GetSecureNoteByID :one
SELECT id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at FROM secure_notes
WHERE id = $1
`

func (q *Queries) GetSecureNoteByID(ctx context.Context, id uuid.UUID) (SecureNote, error) {
	row := q.db.QueryRowContext(ctx, getSecureNoteByID, id)
	var i SecureNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.EncryptedContent,
		&i.EncryptionMetadata,
		&i.IsLocked,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecureNotesByOwner = `-- name: GetSecureNotesByOwner :many
SELECT id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at FROM secure_notes
WHERE owner_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetSecureNotesByOwner(ctx context.Context, ownerID uuid.UUID) ([]SecureNote, error) {
	rows, err := q.db.QueryContext(ctx, getSecureNotesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecureNote
	for rows.Next() {
		var i SecureNote
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.EncryptedContent,
			&i.EncryptionMetadata,
			&i.IsLocked,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSecureNotes = `-- name: SearchSecureNotes :many
SELECT id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at FROM secure_notes
WHERE owner_id = $1 AND title ILIKE $2
ORDER BY updated_at DESC
`

type SearchSecureNotesParams struct {
	OwnerID uuid.UUID
	Title   string
}

func (q *Queries) SearchSecureNotes(ctx context.Context, arg SearchSecureNotesParams) ([]SecureNote, error) {
	rows, err := q.db.QueryContext(ctx, searchSecureNotes, arg.OwnerID, arg.Title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecureNote
	for rows.Next() {
		var i SecureNote
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.EncryptedContent,
			&i.EncryptionMetadata,
			&i.IsLocked,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteAccess = `-- name: UpdateNoteAccess :exec
UPDATE secure_notes
SET last_accessed_at = $2
WHERE id = $1
`

type UpdateNoteAccessParams struct {
	ID             uuid.UUID
	LastAccessedAt sql.NullTime
}

func (q *Queries) UpdateNoteAccess(ctx context.Context, arg UpdateNoteAccessParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteAccess, arg.ID, arg.LastAccessedAt)
	return err
}

const updateNoteLock = `-- name: UpdateNoteLock :one
UPDATE secure_notes
SET is_locked = $2,
    last_accessed_at = $3,
    updated_at = $4
WHERE id = $1 AND owner_id = $5
RETURNING id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at
`

type UpdateNoteLockParams struct {
	ID             uuid.UUID
	IsLocked       sql.NullBool
	LastAccessedAt sql.NullTime
	UpdatedAt      time.Time
	OwnerID        uuid.UUID
}

func (q *Queries) UpdateNoteLock(ctx context.Context, arg UpdateNoteLockParams) (SecureNote, error) {
	row := q.db.QueryRowContext(ctx, updateNoteLock,
		arg.ID,
		arg.IsLocked,
		arg.LastAccessedAt,
		arg.UpdatedAt,
		arg.OwnerID,
	)
	var i SecureNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.EncryptedContent,
		&i.EncryptionMetadata,
		&i.IsLocked,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSecureNote = `-- name: UpdateSecureNote :one
UPDATE secure_notes
SET title = $2,
    encrypted_content = $3,
    encryption_metadata = $4,
    is_locked = $5,
    updated_at = $6
WHERE id = $1 AND owner_id = $7
RETURNING id, owner_id, title, encrypted_content, encryption_metadata, is_locked, last_accessed_at, created_at, updated_at
`

type UpdateSecureNoteParams struct {
	ID                 uuid.UUID
	Title              string
	EncryptedContent   string
	EncryptionMetadata string
	IsLocked           sql.NullBool
	UpdatedAt          time.Time
	OwnerID            uuid.UUID
}

func (q *Queries) UpdateSecureNote(ctx context.Context, arg UpdateSecureNoteParams) (SecureNote, error) {
	row := q.db.QueryRowContext(ctx, updateSecureNote,
		arg.ID,
		arg.Title,
		arg.EncryptedContent,
		arg.EncryptionMetadata,
		arg.IsLocked,
		arg.UpdatedAt,
		arg.OwnerID,
	)
	var i SecureNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.EncryptedContent,
		&i.EncryptionMetadata,
		&i.IsLocked,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
