// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createShare = `-- name: CreateShare :one
INSERT INTO file_shares (file_id, shared_with_user_id, wrapped_key, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, file_id, shared_with_user_id, wrapped_key, created_at
`

type CreateShareParams struct {
	FileID           uuid.NullUUID
	SharedWithUserID uuid.NullUUID
	WrappedKey       string
	CreatedAt        time.Time
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (FileShare, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.FileID,
		arg.SharedWithUserID,
		arg.WrappedKey,
		arg.CreatedAt,
	)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedWithUserID,
		&i.WrappedKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM file_shares
WHERE file_id = $1 AND shared_with_user_id = $2
`

type DeleteShareParams struct {
	FileID           uuid.NullUUID
	SharedWithUserID uuid.NullUUID
}

func (q *Queries) DeleteShare(ctx context.Context, arg DeleteShareParams) error {
	_, err := q.db.ExecContext(ctx, deleteShare, arg.FileID, arg.SharedWithUserID)
	return err
}

const getFilesBySharedWithUser = `-- name: GetFilesBySharedWithUser :many
SELECT f.id, f.owner_id, f.filename, f.file_path, f.file_size, f.encrypted_metadata, f.current_key_version, f.created_at, f.updated_at, f.starred, f.drop_source_id FROM files f
INNER JOIN file_shares fs ON f.id = fs.file_id
WHERE fs.shared_with_user_id = $1
ORDER BY f.created_at DESC
`

func (q *Queries) GetFilesBySharedWithUser(ctx context.Context, sharedWithUserID uuid.NullUUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesBySharedWithUser, sharedWithUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedMetadata,
			&i.CurrentKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Starred,
			&i.DropSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShareByFileAndUser = `-- name: GetShareByFileAndUser :one
SELECT id, file_id, shared_with_user_id, wrapped_key, created_at FROM file_shares
WHERE file_id = $1 AND shared_with_user_id = $2
`

type GetShareByFileAndUserParams struct {
	FileID           uuid.NullUUID
	SharedWithUserID uuid.NullUUID
}

func (q *Queries) GetShareByFileAndUser(ctx context.Context, arg GetShareByFileAndUserParams) (FileShare, error) {
	row := q.db.QueryRowContext(ctx, getShareByFileAndUser, arg.FileID, arg.SharedWithUserID)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedWithUserID,
		&i.WrappedKey,
		&i.CreatedAt,
	)
	return i, err
}

const getSharesByFileID = `-- name: GetSharesByFileID :many
SELECT id, file_id, shared_with_user_id, wrapped_key, created_at FROM file_shares
WHERE file_id = $1
`

func (q *Queries) GetSharesByFileID(ctx context.Context, fileID uuid.NullUUID) ([]FileShare, error) {
	rows, err := q.db.QueryContext(ctx, getSharesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedWithUserID,
			&i.WrappedKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
