// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
  owner_id,
  name,
  color,
  created_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, color, created_at
`

type CreateTagParams struct {
	OwnerID   uuid.UUID
	Name      string
	Color     sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.OwnerID,
		arg.Name,
		arg.Color,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND owner_id = $2
`

type DeleteTagParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.OwnerID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, owner_id, name, color, created_at FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, owner_id, name, color, created_at FROM tags
WHERE owner_id = $1 AND name = $2
`

type GetTagByNameParams struct {
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, arg.OwnerID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsByOwner = `-- name: GetTagsByOwner :many
SELECT id, owner_id, name, color, created_at FROM tags
WHERE owner_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTagsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, color = $3
WHERE id = $1 AND owner_id = $4
RETURNING id, owner_id, name, color, created_at
`

type UpdateTagParams struct {
	ID      uuid.UUID
	Name    string
	Color   sql.NullString
	OwnerID uuid.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.OwnerID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
