// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const clearDropSourceFromFiles = `-- name: ClearDropSourceFromFiles :exec
UPDATE files SET drop_source_id = NULL WHERE drop_source_id = $1
`

func (q *Queries) ClearDropSourceFromFiles(ctx context.Context, dropSourceID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, clearDropSourceFromFiles, dropSourceID)
	return err
}

const createUploadToken = `-- name: CreateUploadToken :one
INSERT INTO upload_tokens (
    token,
    owner_user_id,
    target_folder_id,
    expires_at,
    max_files,
    files_uploaded,
    used,
    created_at,
    password_hash,
    raw_encryption_key,
    link_name,
    pin_wrapped_key
)
VALUES ($1, $2, $3, $4, $5, 0, FALSE, NOW(), $6, $7, $8, $9)
RETURNING id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key
`

type CreateUploadTokenParams struct {
	Token            string
	OwnerUserID      uuid.UUID
	TargetFolderID   uuid.UUID
	ExpiresAt        sql.NullTime
	MaxFiles         sql.NullInt32
	PasswordHash     sql.NullString
	RawEncryptionKey sql.NullString
	LinkName         sql.NullString
	PinWrappedKey    sql.NullString
}

func (q *Queries) CreateUploadToken(ctx context.Context, arg CreateUploadTokenParams) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, createUploadToken,
		arg.Token,
		arg.OwnerUserID,
		arg.TargetFolderID,
		arg.ExpiresAt,
		arg.MaxFiles,
		arg.PasswordHash,
		arg.RawEncryptionKey,
		arg.LinkName,
		arg.PinWrappedKey,
	)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}

const deleteUploadToken = `-- name: DeleteUploadToken :exec
DELETE FROM upload_tokens
WHERE id = $1
`

func (q *Queries) DeleteUploadToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUploadToken, id)
	return err
}

const expireToken = `-- name: ExpireToken :one
UPDATE upload_tokens
SET expires_at = NOW()
WHERE id = $1
RETURNING id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key
`

func (q *Queries) ExpireToken(ctx context.Context, id uuid.UUID) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, expireToken, id)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}

const getFilesByDropToken = `-- name: GetFilesByDropToken :many
SELECT
    f.id,
    f.filename,
    f.file_size,
    f.created_at,
    u.token as drop_token,
    fol.name as folder_name
FROM files f
INNER JOIN upload_tokens u ON f.drop_source_id = u.id
INNER JOIN folders fol ON u.target_folder_id = fol.id
WHERE u.token = $1
ORDER BY f.created_at DESC
`

type GetFilesByDropTokenRow struct {
	ID         uuid.UUID
	Filename   string
	FileSize   int64
	CreatedAt  time.Time
	DropToken  string
	FolderName string
}

func (q *Queries) GetFilesByDropToken(ctx context.Context, token string) ([]GetFilesByDropTokenRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByDropToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByDropTokenRow
	for rows.Next() {
		var i GetFilesByDropTokenRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FileSize,
			&i.CreatedAt,
			&i.DropToken,
			&i.FolderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadTokenByID = `-- name: GetUploadTokenByID :one
SELECT id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key FROM upload_tokens
WHERE id = $1
`

func (q *Queries) GetUploadTokenByID(ctx context.Context, id uuid.UUID) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, getUploadTokenByID, id)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}

const getUploadTokenByToken = `-- name: GetUploadTokenByToken :one
SELECT id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key FROM upload_tokens
WHERE token = $1
`

func (q *Queries) GetUploadTokenByToken(ctx context.Context, token string) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, getUploadTokenByToken, token)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}

const incrementTokenFileCount = `-- name: IncrementTokenFileCount :one
UPDATE upload_tokens
SET files_uploaded = files_uploaded + 1
WHERE id = $1
RETURNING id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key
`

func (q *Queries) IncrementTokenFileCount(ctx context.Context, id uuid.UUID) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, incrementTokenFileCount, id)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}

const listUploadTokensByOwner = `-- name: ListUploadTokensByOwner :many
SELECT id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key FROM upload_tokens
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUploadTokensByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]UploadToken, error) {
	rows, err := q.db.QueryContext(ctx, listUploadTokensByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadToken
	for rows.Next() {
		var i UploadToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.OwnerUserID,
			&i.TargetFolderID,
			&i.ExpiresAt,
			&i.MaxFiles,
			&i.FilesUploaded,
			&i.Used,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.RawEncryptionKey,
			&i.LinkName,
			&i.PinWrappedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenUsed = `-- name: MarkTokenUsed :one
UPDATE upload_tokens
SET used = TRUE
WHERE id = $1
RETURNING id, token, owner_user_id, target_folder_id, expires_at, max_files, files_uploaded, used, created_at, password_hash, raw_encryption_key, link_name, pin_wrapped_key
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id uuid.UUID) (UploadToken, error) {
	row := q.db.QueryRowContext(ctx, markTokenUsed, id)
	var i UploadToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerUserID,
		&i.TargetFolderID,
		&i.ExpiresAt,
		&i.MaxFiles,
		&i.FilesUploaded,
		&i.Used,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.RawEncryptionKey,
		&i.LinkName,
		&i.PinWrappedKey,
	)
	return i, err
}
