// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name,
  last_name,
  username,
  email,
  password_hash,
  public_key,
  private_key_encrypted,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted
`

type CreateUserParams struct {
	FirstName           string
	LastName            string
	Username            string
	Email               string
	PasswordHash        string
	PublicKey           string
	PrivateKeyEncrypted string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.PublicKey,
		arg.PrivateKeyEncrypted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserAsAdmin = `-- name: DeleteUserAsAdmin :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserAsAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserAsAdmin, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted FROM users
ORDER BY created_at DESC
`

// Admin queries
func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.PublicKey,
			&i.PrivateKeyEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.PinHash,
			&i.PinSetAt,
			&i.PrivateKeyPinEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const getUserPINStatus = `-- name: GetUserPINStatus :one
SELECT pin_hash, pin_set_at FROM users
WHERE id = $1
`

type GetUserPINStatusRow struct {
	PinHash  sql.NullString
	PinSetAt sql.NullTime
}

func (q *Queries) GetUserPINStatus(ctx context.Context, id uuid.UUID) (GetUserPINStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPINStatus, id)
	var i GetUserPINStatusRow
	err := row.Scan(&i.PinHash, &i.PinSetAt)
	return i, err
}

const getUserPublicKeyByID = `-- name: GetUserPublicKeyByID :one
SELECT id, public_key FROM users
WHERE id = $1
`

type GetUserPublicKeyByIDRow struct {
	ID        uuid.UUID
	PublicKey string
}

func (q *Queries) GetUserPublicKeyByID(ctx context.Context, id uuid.UUID) (GetUserPublicKeyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPublicKeyByID, id)
	var i GetUserPublicKeyByIDRow
	err := row.Scan(&i.ID, &i.PublicKey)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, first_name, last_name, created_at, updated_at
FROM users
WHERE
  LOWER(username) LIKE LOWER($1) OR
  LOWER(email) LIKE LOWER($1) OR
  LOWER(first_name) LIKE LOWER($1) OR
  LOWER(last_name) LIKE LOWER($1)
ORDER BY created_at DESC
LIMIT $2
`

type SearchUsersParams struct {
	Lower string
	Limit int32
}

type SearchUsersRow struct {
	ID        uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// User search query
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrivateKeyPinEncrypted = `-- name: SetPrivateKeyPinEncrypted :exec
UPDATE users
SET private_key_pin_encrypted = $2
WHERE id = $1
`

type SetPrivateKeyPinEncryptedParams struct {
	ID                     uuid.UUID
	PrivateKeyPinEncrypted sql.NullString
}

func (q *Queries) SetPrivateKeyPinEncrypted(ctx context.Context, arg SetPrivateKeyPinEncryptedParams) error {
	_, err := q.db.ExecContext(ctx, setPrivateKeyPinEncrypted, arg.ID, arg.PrivateKeyPinEncrypted)
	return err
}

const setUserPIN = `-- name: SetUserPIN :exec
UPDATE users
SET pin_hash = $2, pin_set_at = $3
WHERE id = $1
`

type SetUserPINParams struct {
	ID       uuid.UUID
	PinHash  sql.NullString
	PinSetAt sql.NullTime
}

func (q *Queries) SetUserPIN(ctx context.Context, arg SetUserPINParams) error {
	_, err := q.db.ExecContext(ctx, setUserPIN, arg.ID, arg.PinHash, arg.PinSetAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  first_name = $2,
  last_name = $3,
  email = $4,
  updated_at = $5
WHERE id = $1
RETURNING id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted
`

type UpdateUserParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const updateUserAsAdmin = `-- name: UpdateUserAsAdmin :one
UPDATE users
SET
  first_name = $2,
  last_name = $3,
  email = $4,
  username = $5,
  updated_at = $6
WHERE id = $1
RETURNING id, first_name, last_name, username, email, password_hash, public_key, private_key_encrypted, created_at, updated_at, is_admin, pin_hash, pin_set_at, private_key_pin_encrypted
`

type UpdateUserAsAdminParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Username  string
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserAsAdmin(ctx context.Context, arg UpdateUserAsAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAsAdmin,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Username,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PinHash,
		&i.PinSetAt,
		&i.PrivateKeyPinEncrypted,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
  password_hash = $2,
  updated_at = $3
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
